include: package:flutter_lints/flutter.yaml

linter:
  rules:
    prefer_single_quotes: true
    prefer_final_in_for_each: true
    prefer_final_locals: true
    prefer_relative_imports: true

analyzer:
  exclude:
    - lib/**/*.g.dart
    - lib/infra/l18n/intl/*.dart