name: drimble
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0+1
environment:
  sdk: '>=2.17.5 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2
  http: ^0.13.5
  flutter_bloc: ^8.1.1
  google_fonts: ^3.0.1
  intl: ^0.17.0
  date_time_picker: ^2.1.0
  shared_preferences: ^2.0.15
  rxdart: ^0.27.5
  auto_route: ^5.0.1
  numberpicker: ^2.1.1
  collection: ^1.16.0
  dotted_border: ^2.0.0+2
  sqflite: ^2.1.0+1
  sqlbrite: ^2.4.0
  path: ^1.8.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.2.0
  auto_route_generator: ^5.0.2
  mockito: ^5.3.2
  faker: ^2.1.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/

flutter_intl:
  enabled: true
  arb_dir: assets/l10n
  class_name: AppLocalizations
  output_dir: lib/infra/l18n
