name: drimble
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: '>=2.17.5 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2
  http: ^0.13.5
  flutter_bloc: ^8.1.1
  isar: 3.0.0-dev.14
  isar_flutter_libs: 3.0.0-dev.14
  google_fonts: ^3.0.1
  intl: ^0.17.0
  date_time_picker: ^2.1.0
  shared_preferences: ^2.0.15
  rxdart: ^0.27.5
  auto_route: ^5.0.1
  numberpicker: ^2.1.1
  collection: ^1.16.0
  dotted_border: ^2.0.0+2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  isar_generator: 3.0.0-dev.14
  build_runner: ^2.2.0
  auto_route_generator: ^5.0.2

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
