name: drimble
description: Make yesterdays hangover the last.
publish_to: "none"
version: 0.1.0+3
environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2
  http: ^1.2.0
  flutter_bloc: ^8.1.1
  google_fonts: ^6.1.0
  intl: any
  intl_utils: ^2.8.7
  shared_preferences: ^2.0.15
  rxdart: ^0.27.5
  auto_route: ^7.8.4
  numberpicker: ^2.1.1
  collection: ^1.16.0
  dotted_border: ^2.0.0+2
  google_sign_in: ^6.2.1
  sign_in_with_apple: ^6.0.0
  json_annotation: ^4.8.1
  uuid: ^4.4.0
  flutter_local_notifications: ^17.1.2
  timezone: ^0.9.3
  flutter_timezone: ^1.0.8
  firebase_core: ^2.31.0
  firebase_auth: ^4.19.5
  cloud_firestore: ^4.17.3
  path_provider: ^2.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  build_runner: ^2.4.9
  auto_route_generator: ^7.3.2
  mockito: ^5.3.2
  faker: ^2.1.0
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/models/

flutter_intl:
  enabled: true
  main_locale: en
  arb_dir: assets/l10n
  class_name: AppLocalizations
  output_dir: lib/infra/l10n
