// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB_70CIcHECgtsh1sWausBuvy1sgncuEyY',
    appId: '1:1061709448056:android:cff7492df3506f0d047e8d',
    messagingSenderId: '1061709448056',
    projectId: 'drimble-5413f',
    storageBucket: 'drimble-5413f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDiYpO8XozEP4CozGXkGk6GGC3YY8j0dpA',
    appId: '1:1061709448056:ios:71427af1401a2efe047e8d',
    messagingSenderId: '1061709448056',
    projectId: 'drimble-5413f',
    storageBucket: 'drimble-5413f.appspot.com',
    androidClientId: '1061709448056-gv9ftu18e1oofvjosu8p06kjotec540e.apps.googleusercontent.com',
    iosClientId: '1061709448056-s810ors7e9dcs30cjalluopfdvcia2bk.apps.googleusercontent.com',
    iosBundleId: 'app.drimble',
  );
}
