import "../../Fastfile"

default_platform(:ios)

platform :ios do
  desc "Submit a new beta build to Firebase App Distribution"
  lane :beta do
    run_cmd(command: "flutter build ipa --release")

    firebase_app_distribution(
      app: "1:159589082657:ios:a3ae69b9b171834122e560",
      ipa_path: "#{root_path}/build/ios/ipa/Drimble.ipa",
      groups: "alpha-testers"
    )
  end
end
